#include "stdio.h"
#include"string.h"
#include "math.h"
#include "mosaicSource/common/common.h"
#include "mosaic3d.h"
static void writeExtraTies(char *extraTieFile,  ShelfMask *shelfMask,double tideCorrection,xyDEM *dem, FILE *fp  , double xmin, double ymin,double xmax,double ymax);

/*
  write a tiepoint file generated by mosaic3d.
*/
unsigned char writeTieFile( outputImageStructure *outputImage, xyDEM *dem,
			    char *outFile,double tieThresh,char *extraTieFile,char *tideFile, int autoSize)
{   
	extern int HemiSphere;
	extern double Rotation;
	float **vXimage,**vYimage,**vZimage;
	ShelfMask *shelfMask;    /* Mask with shelf and grounding zone */
	unsigned char sMask;
	double x,y,z,lat,lon;
	double  v,vz;
	double xmin,ymin,xmax,ymax;
	double tideCorrection;
	int i,j; 
	int lineCount,eod;
	FILE *fp,*fpIn;
	double errorV,eThresh;
	float **errorX,**errorY;
	char buf[512];
	fprintf(stderr,"Writing Tie File \n");
	shelfMask = outputImage->shelfMask;
	vXimage = (float **)outputImage->image;
	vYimage = (float **)outputImage->image2;
	vZimage = (float **)outputImage->image3;
	errorX = (float **)outputImage->errorX;
	errorY = (float **)outputImage->errorY;
	eThresh=120.;
	/* Tide correction */
	if(tideFile != NULL) {
		lineCount=0;
		fpIn=openInputFile(tideFile);
		if(fpIn != NULL) {
			lineCount=getDataString(fpIn,lineCount,buf,&eod);
			sscanf(buf,"%lf",&(tideCorrection));
		} else {
			tideCorrection=0.0;
		}
		fprintf(stderr,"Tide correction value: %f\n",tideCorrection);
		fclose(fpIn);
	} else tideCorrection=0.0;
	fp=fopen(outFile,"w");
	/* 
	   If autoscale, then output everything. Otherwise assume prescribed limits and only
	   output for that region
	*/
	if( autoSize == TRUE) {
		xmin=-1.0e9; ymin=-1.e9;
		xmax=1.0e9; ymax=1.e9;		
	} else {
		xmin=outputImage->originX*0.001;
		ymin=outputImage->originY*0.001;;
		xmax=(outputImage->originX+outputImage->xSize * outputImage->deltaX)*0.001;
		ymax=(outputImage->originY+outputImage->ySize * outputImage->deltaY)*0.001;
	}
	fprintf(stderr,"min,max = %lf %lf %lf %lf\n",xmin,ymin,xmax,ymax);
	fprintf(stderr,"%i %i %f\n",outputImage->ySize,outputImage->xSize,eThresh);
	for (i=0; i < outputImage->ySize; i++) {
		y = (outputImage->originY + i*outputImage->deltaY) * MTOKM;
		for(j=0; j < outputImage->xSize; j++) {
			x = (outputImage->originX + j*outputImage->deltaX) * MTOKM;
			/* Valid data so output */
			v=  sqrt( vXimage[i][j]*vXimage[i][j] + vYimage[i][j]*vYimage[i][j]);
			/* NOTE ERRORS already squared */
			errorV=sqrt(errorX[i][j] + errorY[i][j]);
			/* If valid point, output */
			if(v < tieThresh && errorV < eThresh) {
				xytoll1(x,y,HemiSphere,&lat,&lon,Rotation,dem->stdLat);
				z = getXYHeight(lat,lon,dem,0.0,ELLIPSOIDAL);
				if(lat > 180) lat -=360.;
				if(shelfMask != NULL) sMask=getShelfMask(shelfMask,x,y);
				else sMask=GROUNDED;
				vz=0.0;
				if(sMask == SHELF) vz += tideCorrection;
				fprintf(fp," %10.5f %10.5f  %7.1f    %8.2f %8.2f %8.3lf\n",lat,lon,z, vXimage[i][j],vYimage[i][j],vz);
			}
		}
	}
	/*
	  Copy ties points from extra ties 
	*/
        if(extraTieFile != NULL)
		writeExtraTies(extraTieFile,  shelfMask, tideCorrection, dem,fp  ,  xmin,  ymin, xmax, ymax);
	fprintf(fp,"&\n");
	fclose(fp);
} 


/*
  This program will write tiepoints previously computed and stored in a file, extraTieFile
*/
static void writeExtraTies(char *extraTieFile,  ShelfMask *shelfMask,double tideCorrection,xyDEM *dem, FILE *fp  , double xmin, double ymin,double xmax,double ymax) {
	extern int HemiSphere;
	extern double Rotation;	 
	FILE *fpIn;	
	double x,y,z,lat,lon;
	char *line,buf[512];
	double vx,vy,vz;
	double d1,d2,d3;
	unsigned char sMask;
	
	fprintf(stderr,"**** ADDING TIEPOINTS FROM: %s *****\n",extraTieFile);
	fpIn = openInputFile(extraTieFile);
	fprintf(fp,";\n; Tiepoints from: %s\n;\n",extraTieFile);
	line=fgets(buf,512,fpIn);
	while(line !=NULL && strchr(line,'&') == NULL) {
		line=fgets(buf,512,fpIn);
		if(sscanf(line,"%lf%lf%lf%lf%lf%lf\n",&lat,&lon,&z,&vx,&vy,&vz) !=6) {
			/* Only 2 valid entries means zero points */
			if(sscanf(line,"%lf%lf\n",&lat,&lon) ==2 && sscanf(line,"%lf%lf%lf",&d1,&d2,&d3) != 3) {
				z = getXYHeight(lat,lon,dem,0.0,ELLIPSOIDAL);
				lltoxy1(lat,lon,&x,&y,Rotation,dem->stdLat);
				/*fprintf(stderr,"%f %f\n",x,y);*/
				if(x >= xmin && x <= xmax && y >= ymin && y <=ymax)
					fprintf(fp,"%10.5f %10.5f  %7.1f    %8.2f %8.2f %8.3f\n", lat,lon,z,0.0,0.0,0.0);
			} else fprintf(stderr,"Not including\n%s\n",line);
		} else {
			lltoxy1(lat,lon,&x,&y,Rotation,dem->stdLat);	 
			if(shelfMask != NULL) {
				sMask=getShelfMask(shelfMask,x,y);
				if(sMask == SHELF) vz += tideCorrection;
			}
			if(x >= xmin && x <= xmax && y >= ymin && y <=ymax)	   
				fprintf(fp,"%10.5f %10.5f  %7.1f    %8.2f %8.2f %8.3f\n",  lat,lon,z,vx,vy,vz);
		}
	}
	fclose(fpIn);		
}
